In [21]:
import numpy as np
import itertools
trials = 200
N = 50
k = 6
b = 4 
score,decision = run(N,b,k,trials,reward_type = 0)


# Generate all combinations of num_elements that sum to target_sum
result = []
    
    # Use combinations_with_replacement to generate numbers that sum to target_sum
for combination in itertools.combinations_with_replacement(range(N+1), k):
        if sum(combination) == N:
            result.append(combination)

combinations = result
# Print the first 5 results to check
for comb in combinations[:5]:
    #print(comb)
    pass

In [22]:
#Individual Reward  
for comb in combinations:
    decision = np.array(comb)
    Nash = True
    for agent_no,total in enumerate(decision):
        Score = total*np.exp(-total/b)
        #print(decision)
        current_total = total
        #print(decision_new)
        #print(Score)
        #print(agent_no)
        if total == 0:
            continue
        decision[agent_no] = decision[agent_no] -1
        for i in range(len(decision)):
            #decision_new[i] = decision[i]+1
            #Calc reward
            New_decision_Total = decision[i]+1
            Reward = New_decision_Total*np.exp(-New_decision_Total/b)
            
            if Reward>Score:
                Nash = False
                #print(agent_no)
                #print(i)
                #print(New_decision_Total)
                #print(Score)
                #print(Reward)
        decision[agent_no] = decision[agent_no] +1
    if Nash==True:
        print("\nFound Nash Equilibrium at:")
        print(decision)
    



Found Nash Equilibrium at:
[ 0 10 10 10 10 10]

Found Nash Equilibrium at:
[8 8 8 8 9 9]


In [23]:
#Global Reward 
decision_new = np.zeros(k) 
for comb in combinations:
    decision = np.array(comb)
    Nash = True
    Score = 0
    #Do global instead of individual
    for agent,total_count in enumerate(decision):
        Score = total_count*np.exp(-total_count/b) +Score
    for agent_no,total in enumerate(decision):
        #Score = total*np.exp(-total/b)
        #print(decision)
        current_total = total
        #print(decision_new)
        #print(Score)
        #print(agent_no)
        if total == 0:
            continue
            
        decision[agent_no] = decision[agent_no] -1
        for i in range(len(decision)):
            decision_new = decision.copy()
            #Calc reward
            Total_count = decision[i].copy()
            decision_new[i] = Total_count+1
            #Reward = New_decision_Total*np.exp(-New_decision_Total/b)
            Reward = 0
            #Now calculate global reward
            for agent_no_rew,total_count_2 in enumerate(decision_new):
                Reward = total_count_2*np.exp(-total_count_2/b) +Reward
                
            #print(Reward)
            #print(decision)
            #print(Score)
            #print(decision_new)
            if Reward>Score:
                #print(agent_no)
                #print(comb)
                Nash = False
                #print(agent_no)
                #print(i)
                #print(decision)
            
                
            
        decision[agent_no] = decision[agent_no] +1
        #print(Score)
    if Nash==True:
        print("\nFound Nash Equilibrium at:")
        print(decision)
        
        pass
        


Found Nash Equilibrium at:
[ 4  4  4  4  4 30]


In [24]:
#Part 3
#Counterfactual 
for comb in combinations:
    decision = np.array(comb)
    Nash = True
    for agent_no,total in enumerate(decision):
        Score = total*np.exp(-total/b)-(total-1)*np.exp(-(total-1)/b)
        #print(decision)
        current_total = total
        #print(decision_new)
        #print(Score)
        #print(agent_no)
        if total == 0:
            continue
        decision[agent_no] = decision[agent_no] -1
        for i in range(len(decision)):
            #decision_new[i] = decision[i]+1
            #Calc reward
            New_decision_Total = decision[i]+1
            Reward = New_decision_Total*np.exp(-New_decision_Total/b)-(New_decision_Total-1)*np.exp(-(New_decision_Total-1)/b)
            
            if Reward>Score:
                Nash = False
                #print(agent_no)
                #print(i)
                #print(New_decision_Total)
                #print(Score)
                #print(Reward)
        decision[agent_no] = decision[agent_no] +1
    if Nash==True:
        print("\nFound Nash Equilibrium at:")
        print(decision)


Found Nash Equilibrium at:
[ 4  4  4  4  4 30]
